const accounts=[
{code:"1000",name:"Bank"},{code:"1100",name:"Prepayments"},{code:"2100",name:"Accruals"},{code:"6000",name:"Professional Fees"},{code:"6100",name:"Insurance Expense"}];
let journals=[];
const presets={
accrual:{date:"2026-09-30",description:"Month-end professional fees accrual",source:"Month-end",lines:[{account:"6000",debit:1200,credit:0},{account:"2100",debit:0,credit:1200}]},
reversal:{date:"2026-10-01",description:"Reverse September professional fees accrual",source:"Month-end",lines:[{account:"2100",debit:1200,credit:0},{account:"6000",debit:0,credit:1200}]},
prepayment:{date:"2026-09-15",description:"Annual insurance paid in advance",source:"Manual",lines:[{account:"1100",debit:1200,credit:0},{account:"1000",debit:0,credit:1200}]},
release:{date:"2026-09-30",description:"September insurance prepayment release",source:"Month-end",lines:[{account:"6100",debit:100,credit:0},{account:"1100",debit:0,credit:100}]}
};
const linesEl=document.getElementById("journalLines");
const money=v=>Number(v||0).toLocaleString("en-GB",{minimumFractionDigits:2,maximumFractionDigits:2});
function options(sel){return accounts.map(a=>`<option value="${a.code}" ${a.code===sel?"selected":""}>${a.code} — ${a.name}</option>`).join("")}
function addLine(line={account:"6000",debit:0,credit:0}){const r=document.createElement("tr");r.innerHTML=`<td><select class="acct">${options(line.account)}</select></td><td><input class="debit" type="number" min="0" step="0.01" value="${line.debit||""}"></td><td><input class="credit" type="number" min="0" step="0.01" value="${line.credit||""}"></td><td><button class="remove">Remove</button></td>`;r.querySelectorAll("input,select").forEach(e=>e.addEventListener("input",refresh));r.querySelector(".remove").onclick=()=>{r.remove();refresh()};linesEl.appendChild(r);refresh()}
function lines(){return [...linesEl.querySelectorAll("tr")].map(r=>({account:r.querySelector(".acct").value,debit:+(r.querySelector(".debit").value||0),credit:+(r.querySelector(".credit").value||0)}))}
function validate(){const ls=lines(),d=ls.reduce((s,x)=>s+x.debit,0),c=ls.reduce((s,x)=>s+x.credit,0),desc=document.getElementById("journalDescription").value.trim(),date=document.getElementById("journalDate").value,lock=document.getElementById("lockDate").value;const balanced=ls.length>=2&&d>0&&Math.abs(d-c)<.005,validAccounts=ls.every(x=>accounts.some(a=>a.code===x.account)),validShape=ls.every(x=>(x.debit>0&&x.credit===0)||(x.credit>0&&x.debit===0)),narrative=!!desc,periodOpen=!lock||!date||date>lock;return{ls,d,c,balanced,validAccounts,validShape,narrative,periodOpen,ok:balanced&&validAccounts&&validShape&&narrative&&periodOpen}}
function refresh(){const v=validate();document.getElementById("debitTotal").textContent=money(v.d);document.getElementById("creditTotal").textContent=money(v.c);document.getElementById("controlChecks").innerHTML=[["Double entry balances",v.balanced],["Accounts are valid",v.validAccounts&&v.validShape],["Narrative present",v.narrative],["Period is open",v.periodOpen]].map(([t,p])=>`<div class="check ${p?"pass":"fail"}">${p?"✓":"✕"} ${t}</div>`).join("")}
function post(){const v=validate(),m=document.getElementById("message");m.className="message";if(!v.ok){m.classList.add("error");m.textContent="Journal not posted. Resolve the failed control checks first.";return}const ref=`JRN-${String(journals.length+1).padStart(4,"0")}`;journals.push({reference:ref,date:document.getElementById("journalDate").value,description:document.getElementById("journalDescription").value.trim(),source:document.getElementById("journalSource").value,postedAt:new Date().toISOString(),lines:v.ls.map(x=>({...x})),total:v.d});render();m.classList.add("success");m.textContent=`${ref} posted successfully and is now visible in the ledger, trial balance and audit trail.`}
function render(){const ledger=document.getElementById("ledgerBody"),entries=journals.flatMap(j=>j.lines.map(l=>({...l,reference:j.reference,date:j.date,description:j.description})));ledger.innerHTML=entries.length?entries.map(e=>`<tr><td>${e.reference}</td><td>${e.date}</td><td>${e.account} — ${accounts.find(a=>a.code===e.account).name}</td><td>${e.description}</td><td>${e.debit?money(e.debit):""}</td><td>${e.credit?money(e.credit):""}</td></tr>`).join(""):`<tr><td colspan="6">No posted journals yet.</td></tr>`;
const mov={};accounts.forEach(a=>mov[a.code]={d:0,c:0});journals.forEach(j=>j.lines.forEach(l=>{mov[l.account].d+=l.debit;mov[l.account].c+=l.credit}));const rows=accounts.map(a=>{const net=mov[a.code].d-mov[a.code].c;return{...a,d:net>0?net:0,c:net<0?-net:0}}).filter(x=>x.d||x.c);document.getElementById("trialBalanceBody").innerHTML=rows.length?rows.map(r=>`<tr><td>${r.code}</td><td>${r.name}</td><td>${r.d?money(r.d):""}</td><td>${r.c?money(r.c):""}</td></tr>`).join(""):`<tr><td colspan="4">No balances yet.</td></tr>`;document.getElementById("tbDebitTotal").textContent=money(rows.reduce((s,r)=>s+r.d,0));document.getElementById("tbCreditTotal").textContent=money(rows.reduce((s,r)=>s+r.c,0));document.getElementById("auditTrail").innerHTML=journals.length?[...journals].reverse().map(j=>`<div class="audit-item"><strong>${j.reference} · £${money(j.total)}</strong><div>${j.description}</div><div class="audit-meta">Journal date: ${j.date}<br>Source: ${j.source}<br>Posted: ${new Date(j.postedAt).toLocaleString("en-GB")}</div></div>`).join(""):`<p>No postings recorded yet.</p>`}
function load(name){const p=presets[name];document.getElementById("journalDate").value=p.date;document.getElementById("journalDescription").value=p.description;document.getElementById("journalSource").value=p.source;linesEl.innerHTML="";p.lines.forEach(addLine);refresh()}
document.getElementById("addLine").onclick=()=>addLine();document.getElementById("postJournal").onclick=post;document.getElementById("lockDate").onchange=refresh;document.getElementById("journalDate").onchange=refresh;document.getElementById("journalDescription").oninput=refresh;document.querySelectorAll("[data-preset]").forEach(b=>b.onclick=()=>load(b.dataset.preset));load("accrual");render();